controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    glove_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters: {}






glove_controller:
  ros__parameters:
    joints:
      - tl0_joint
      - tl1_joint
      - tl2_joint
      - tl3_joint
      - f1l0_joint
      - f1l1_joint
      - f1l2_joint
      - f1l3_joint
      - f2l0_joint
      - f2l1_joint
      - f2l2_joint
      - f2l3_joint
    gains:
      tl0_joint: {p: 5.0, i: 0.1, d: 0.5}
      tl1_joint: {p: 5.0, i: 0.1, d: 0.5}
      tl2_joint: {p: 5.0, i: 0.1, d: 0.5}
      tl3_joint: {p: 5.0, i: 0.1, d: 0.5}
      f1l0_joint: {p: 5.0, i: 0.1, d: 0.5}
      f1l1_joint: {p: 5.0, i: 0.1, d: 0.5}
      f1l2_joint: {p: 5.0, i: 0.1, d: 0.5}
      f1l3_joint: {p: 5.0, i: 0.1, d: 0.5}
      f2l0_joint: {p: 5.0, i: 0.1, d: 0.5}
      f2l1_joint: {p: 5.0, i: 0.1, d: 0.5}
      f2l2_joint: {p: 5.0, i: 0.1, d: 0.5}
      f2l3_joint: {p: 5.0, i: 0.1, d: 0.5}
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
